project_id = "zecnlseiutpbbmklulue"

[functions.binance-api]
verify_jwt = false

[functions.pine-script-engine]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.binance-websocket-proxy]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false